const products=window.DIGILOG_CATALOG||[
 {id:1,name:'ESP32 WiFi + Bluetooth Dev Board',price:18.95,old:22.95,type:'boards',rating:128,badge:'BEST SELLER',image:'assets/products/esp32-dev-board.jpg'},
 {id:2,name:'Auto-Range Digital Multimeter',price:49.50,old:59.00,type:'tools',rating:84,badge:'SAVE 16%',image:'assets/products/digital-multimeter.jpg'},
 {id:3,name:'HC-SR04 Ultrasonic Distance Sensor',price:6.75,old:null,type:'sensors',rating:213,badge:'POPULAR',image:'assets/products/hc-sr04-sensor.jpg'},
 {id:4,name:'Temperature-Controlled Soldering Station',price:72.00,old:84.00,type:'tools',rating:67,badge:'NEW',image:'assets/products/soldering-station.jpg'},
 {id:5,name:'Raspberry Pi Pico RP2040 Board',price:12.50,old:null,type:'boards',rating:96,badge:'POPULAR',image:'https://littlebirdelectronics.com.au/cdn/shop/products/image_36532361-0648-481d-9696-82ea76bde64f_1200x1200.jpg?v=1698712861'},
 {id:6,name:'830-Point Solderless Breadboard',price:8.90,old:10.50,type:'boards',rating:99,badge:'SAVE 15%',image:'https://core-electronics.com.au/media/catalog/product/c/e/ce07065-1.jpg'},
 {id:7,name:'DHT22 Temperature & Humidity Sensor',price:11.50,old:null,type:'sensors',rating:144,badge:'POPULAR',image:'https://cdn11.bigcommerce.com/s-am5zt8xfow/images/stencil/1280x1280/products/685/1613/apibve1ur__58779.1554986582.jpg?c=2'},
 {id:8,name:'SG90 Micro Servo Motor',price:9.25,old:12.00,type:'sensors',rating:176,badge:'BEST SELLER',image:'https://arrowtechcart.com/cdn/shop/files/Arrowtechcart_TowerProSG90Mini-MicroServoMotor4.webp?v=1756145620&width=1445'},
 {id:9,name:'NEMA 17 Stepper Motor',price:18.75,old:null,type:'tools',rating:61,badge:'NEW',image:'https://3d.nice-cdn.com/upload/image/product/large/default/elegoo-stepper-motor-42-40-round-shaft-641422-de.jpg'},
 {id:10,name:'1.3-inch OLED Display Module',price:14.00,old:17.00,type:'sensors',rating:83,badge:'SAVE 18%',image:'https://www.hicenda.com/Uploads/688c794157c78.jpg'},
 {id:11,name:'Male-to-Female Jumper Wire Set',price:6.95,old:null,type:'boards',rating:154,badge:'ESSENTIAL',image:'https://www.hwlibre.com/wp-content/uploads/2022/02/cable-jumper-1.jpg'},
 {id:12,name:'HC-SR501 PIR Motion Sensor',price:7.50,old:null,type:'sensors',rating:152,badge:'POPULAR',image:'https://robu.in/wp-content/uploads/2016/02/PIR-Motion-Sensor-Detector-Module-HC-SR501-2.jpg'},
 {id:13,name:'16x2 Character LCD Module',price:10.95,old:13.50,type:'sensors',rating:117,badge:'SAVE 19%',image:'https://cz.lnwfile.com/_/cz/_raw/g3/23/4g.jpg'},
 {id:14,name:'AC/DC Digital Clamp Meter',price:58.00,old:null,type:'tools',rating:73,badge:'PRO',image:'https://www.tvcalx.co.uk/wp-content/uploads/2013/05/ACC-0020-Website-scaled.jpg'},
 {id:15,name:'5V Single-Channel Relay Module',price:5.50,old:null,type:'sensors',rating:189,badge:'BEST SELLER',image:'https://down-br.img.susercontent.com/file/0a976caa831786066d822db4f362c7c6'},
 {id:16,name:'30V 10A Adjustable Bench Power Supply',price:119.00,old:139.00,type:'tools',rating:48,badge:'SAVE 14%',image:'https://i.ebayimg.com/images/g/VnQAAeSwZ0Vpfx0J/s-l1200.jpg'},
 {id:17,name:'L298N Dual Motor Driver Module',price:12.75,old:null,type:'boards',rating:135,badge:'ROBOTICS',image:'https://www.mecabot.com/cdn/shop/files/Modulo_Puente_H_L298N-02.png?v=1750869805&width=1445'},
 {id:18,name:'10K Rotary Potentiometer Module',price:4.25,old:null,type:'sensors',rating:66,badge:'NEW',image:'https://i.ebayimg.com/images/g/oOsAAOSwNTxgpg2c/s-l400.png'}
];
let cart=JSON.parse(localStorage.getItem('digilog-cart')||'[]');let visible=24;let current='all';
const grid=document.querySelector('#product-grid');
function renderProducts(){const list=products.filter(p=>current==='all'||p.type===current).slice(0,visible);grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-visual">${p.badge?`<span class="product-badge">${p.badge}</span>`:''}<button class="wishlist" data-id="${p.id}" aria-label="Add ${p.name} to wishlist">♡</button><img class="product-photo" src="${p.image}" alt="${p.name}" loading="lazy"></div><div class="product-info">${p.rating?`<div class="stars">★★★★★ <span>(${p.rating})</span></div>`:''}<h3>${p.name}</h3><div class="price-row"><div><strong>$${p.price.toFixed(2)}</strong> ${p.old?`<del>$${p.old.toFixed(2)}</del>`:''}</div><button class="add-cart" data-id="${p.id}" aria-label="Add ${p.name} to cart">+</button></div></div></article>`).join('');document.querySelector('#show-more').style.display=list.length>=products.filter(p=>current==='all'||p.type===current).length?'none':'inline-flex'}
function renderCart(){localStorage.setItem('digilog-cart',JSON.stringify(cart));const box=document.querySelector('#cart-items');const total=cart.reduce((s,p)=>s+p.price,0);document.querySelector('#cart-count').textContent=cart.length;document.querySelector('#cart-total').textContent=`$${total.toFixed(2)}`;box.innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-item"><div class="cart-thumb">D</div><div><h4>${p.name}</h4><small>$${p.price.toFixed(2)}</small></div><button class="remove-item" data-index="${i}">×</button></div>`).join(''):'<p class="empty-cart">Your cart is ready for a new project.</p>'}
function toast(message){const t=document.querySelector('.toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function openCart(open=true){document.querySelector('.cart-drawer').classList.toggle('open',open);document.querySelector('.overlay').classList.toggle('show',open);document.querySelector('.cart-drawer').setAttribute('aria-hidden',String(!open))}
document.addEventListener('click',e=>{const add=e.target.closest('.add-cart');if(add){const p=products.find(x=>x.id===Number(add.dataset.id));cart.push(p);renderCart();toast(`${p.name} added to cart`)}const wish=e.target.closest('.wishlist');if(wish){wish.classList.toggle('liked');wish.textContent=wish.classList.contains('liked')?'♥':'♡';toast(wish.classList.contains('liked')?'Saved to your wishlist':'Removed from wishlist')}const remove=e.target.closest('.remove-item');if(remove){cart.splice(Number(remove.dataset.index),1);renderCart()}if(e.target.closest('.cart-toggle'))openCart();if(e.target.closest('.cart-close')||e.target.classList.contains('overlay'))openCart(false)});
document.querySelectorAll('.product-tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.product-tabs .active').classList.remove('active');btn.classList.add('active');current=btn.dataset.filter;visible=24;renderProducts()}));
document.querySelector('#show-more').addEventListener('click',()=>{visible=Math.min(visible+24,products.length);renderProducts()});
document.querySelector('#search-form').addEventListener('submit',e=>{e.preventDefault();const q=document.querySelector('#search-input').value.trim().toLowerCase();if(!q)return;const matches=products.filter(p=>p.name.toLowerCase().includes(q));grid.innerHTML=matches.length?matches.map(p=>`<article class="product-card"><div class="product-visual"><img class="product-photo" src="${p.image}" alt="${p.name}"></div><div class="product-info"><div class="stars">★★★★★ <span>(${p.rating})</span></div><h3>${p.name}</h3><div class="price-row"><strong>$${p.price.toFixed(2)}</strong><button class="add-cart" data-id="${p.id}">+</button></div></div></article>`).join(''):'<p>No products found. Try “board”, “sensor”, or “meter”.</p>';document.querySelector('#products').scrollIntoView()});
document.querySelector('#newsletter-form').addEventListener('submit',e=>{e.preventDefault();e.target.reset();toast('Welcome to the Digilog club!')});
document.querySelector('.menu-button').addEventListener('click',()=>document.querySelector('.search').classList.toggle('mobile-open'));
document.querySelector('.checkout').addEventListener('click',()=>{if(!cart.length){toast('Add a product before checking out.');return}window.location.href='checkout.html'});
renderProducts();renderCart();

